# Generated by Django 4.2.4 on 2023-08-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=255, unique=True, verbose_name='Student Email')),
                ('vendor_email', models.EmailField(max_length=255, unique=True, verbose_name='Vendor Email')),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('is_vendor', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('profile_image', models.ImageField(default='static/images/profile.jpg', upload_to='uploads/profile')),
                ('student_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.university')),
            ],
        ),
    ]
